version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 
    commands:
      - echo Installing dependencies...
      - cd backend # Assuming your backend is in a 'backend' folder
      - npm install
      - cd ../frontend # Assuming your frontend is in a 'frontend' folder
      - npm install
      - echo "REACT_APP_BASE_URL is: $REACT_APP_BASE_URL"
      - echo Creating .env file for React frontend...
      - echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env
      - echo "REACT_APP_RAZORPAY_KEY_ID=$REACT_APP_RAZORPAY_KEY_ID" >> .env
  build:
    commands:
      - echo Building React frontend...
      - npm run build # Assumes 'build' script in frontend/package.json
      - echo Copying frontend build to backend public directory...
      - mkdir -p ../backend/public
      - cp -r build/* ../backend/public/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
      - cd ../backend
      - cp ../appspec.yml .
      - cp -r ../scripts .

artifacts:
  files:
    - '**/*'
  base-directory: backend